In [1]:
#creat ea 2x2 array
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [2]:
import numpy as np

np.array(arr)

array([[1, 2],
       [3, 4]])

In [3]:
import torch

torch.Tensor(arr)

C:\Users\91902\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([[1., 2.],
        [3., 4.]])

In [4]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [5]:
np.random.rand(2, 2)

array([[0.46223094, 0.98972697],
       [0.06271844, 0.36423958]])

In [6]:
torch.rand(2, 2)

tensor([[0.7967, 0.4562],
        [0.7542, 0.5508]])

In [10]:
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [11]:
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [13]:
torch.rand(2, 2)

tensor([[0.4556, 0.6323],
        [0.3489, 0.4017]])

In [14]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

In [15]:
np_array = np.ones((2, 2))
print(np_array)

[[1. 1.]
 [1. 1.]]


In [16]:
print(type(np_array))

<class 'numpy.ndarray'>


In [17]:
torch_tensor = torch.from_numpy(np_array)

In [18]:
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [19]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [21]:
# Data types matter: intentional error
np_array_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]])

In [22]:
np_array_new = np.ones((2, 2), dtype=np.uint8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)

In [23]:
torch_tensor =torch.ones(2, 2)
type(torch_tensor)

torch.Tensor

In [24]:
torch_to_numpy = torch_tensor.numpy()
type(torch_to_numpy)

numpy.ndarray

In [26]:
tensor_cpu = torch.ones(2, 2)
tensor_cpu


tensor([[1., 1.],
        [1., 1.]])

In [30]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
tensor_cpu.to(device)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [31]:
# GPU to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

In [35]:
a = torch.ones(2, 2)
print(a)
print(a.size())

tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])


In [36]:
a.view(4)

tensor([1., 1., 1., 1.])

In [37]:
a.view(4).size()

torch.Size([4])

In [46]:
a = torch.ones(2, 2)
b = torch.ones(2, 2)
print(a)


tensor([[1., 1.],
        [1., 1.]])


In [47]:
c = a + b
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [48]:
c = torch.add(a, b)
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [49]:
print('Oldc tensor')
print(c)

c.add_(a)

print('_'*60)
print('New c tensor')
print(c)

Oldc tensor
tensor([[2., 2.],
        [2., 2.]])
____________________________________________________________
New c tensor
tensor([[3., 3.],
        [3., 3.]])


In [50]:
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [51]:
a -b

tensor([[0., 0.],
        [0., 0.]])

In [52]:
print(a.sub(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [53]:
print(a.sub_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


In [54]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10] )
a.size()

a.mean(dim = 0)

tensor(5.5000)

In [55]:
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
a.size()

torch.Size([2, 10])

In [56]:
a.mean(dim=1)

tensor([5.5000, 5.5000])

In [57]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std(dim=0)

tensor(3.0277)